// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfELx1cnLg6-Bj4IQIYX4hvgVgOLblUg8',
    appId: '1:892676552587:web:a83633a93648952561e18e',
    messagingSenderId: '892676552587',
    projectId: 'task-management-ff412',
    authDomain: 'task-management-ff412.firebaseapp.com',
    storageBucket: 'task-management-ff412.firebasestorage.app',
    measurementId: 'G-0JWNGW88KJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYrsNelma32WkMd4hRcnBx2tcPvIYJyjw',
    appId: '1:892676552587:android:9ef59aa6e07c635061e18e',
    messagingSenderId: '892676552587',
    projectId: 'task-management-ff412',
    storageBucket: 'task-management-ff412.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfUwCW77PBkf91C3iuj8s44qY5OmFr6DM',
    appId: '1:892676552587:ios:311967fc55ca994861e18e',
    messagingSenderId: '892676552587',
    projectId: 'task-management-ff412',
    storageBucket: 'task-management-ff412.firebasestorage.app',
    iosBundleId: 'com.example.newTaskManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfUwCW77PBkf91C3iuj8s44qY5OmFr6DM',
    appId: '1:892676552587:ios:311967fc55ca994861e18e',
    messagingSenderId: '892676552587',
    projectId: 'task-management-ff412',
    storageBucket: 'task-management-ff412.firebasestorage.app',
    iosBundleId: 'com.example.newTaskManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfELx1cnLg6-Bj4IQIYX4hvgVgOLblUg8',
    appId: '1:892676552587:web:4f150e275c99854361e18e',
    messagingSenderId: '892676552587',
    projectId: 'task-management-ff412',
    authDomain: 'task-management-ff412.firebaseapp.com',
    storageBucket: 'task-management-ff412.firebasestorage.app',
    measurementId: 'G-S40ECBBQRV',
  );
}
